# Site Specific Configuration
name: Nicola Tommasini
description: Personal Github page
url: https://nicolatommasini.github.io/
author: NicolaTommasini
timezone: Europe/Rome
timezone_short: CEST

# Keywords
keywords: ['science', 'technology', 'math', 'computer science', 'cs', 'AI', 'ML', 'finance']

# Analytics (Plausible requires sign-up)
analytics:
  plausible:
    enabled: false
    site_fqdn: 'your.site.fqdn'
    script_source: 'https://plausible.io/js/script.js'

# Styling
sass:
  sass_dir: _sass
  style: expanded # compact, expanded or compressed

# Paginate
pagination:
  enabled: true
  # Value set low for demonstration purposes
  per_page: 3
  sort_field: 'date'
  sort_reverse: true

# Category Paginating
autopages:
  enabled: true
  categories:
    title: 'Posts in category :cat'
    permalink: '/category/:cat'
    silent: false

# Exclusions
exclude: [ 'README.md', 'COPYING' ]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

